#!/bin/bash

register() {
    kubectl exec -n spire spire-server-0 -c spire-server -- /opt/spire/bin/spire-server entry create $@
}

# Create entry for kubernetes nodes
register \
    -spiffeID spiffe://example.k8s.local/cluster \
    -selector k8s_sat:cluster:example.k8s.local \
    -selector k8s_sat:agent_ns:spire \
    -selector k8s_sat:agent_sa:spire-agent \
    -node

# Create entry for postgres (customer-db)
register \
     -parentID spiffe://example.k8s.local/cluster \
     -spiffeID spiffe://example.k8s.local/customer-db \
     -selector k8s:container-name:spiffe-helper \
     -selector k8s:pod-label:app:postgres \
     -ttl 60

# Create entry for customer API service (customer-service)
register \
     -parentID spiffe://example.k8s.local/cluster \
     -spiffeID spiffe://example.k8s.local/customer-service \
     -selector k8s:container-name:spiffe-helper \
     -selector k8s:pod-label:app:customer \
     -dns symuser \
     -ttl 60
